"""
tests/mock_activity.py
======================
Standalone CLI utility to generate a realistic dummy workspace and simulate
file-system activity for integration testing of the SPD Analysis Engine.

What it does
------------
1. Creates a temporary workspace with two Python source files:
   ``main.py`` and ``utils.py``.
2. (Optionally) Starts a project worker via the Supervisor API and waits for
   it to emit a startup heartbeat.
3. Simulates a configurable number of timed edit bursts by writing randomised
   content changes to the workspace files.
4. Reports heartbeat counts and session DB event counts at the end.
5. Stops the worker cleanly and prints a final summary.

Usage
-----
::

    # Scaffold a workspace, start a worker, run 5 edit bursts, stop:
    python tests/mock_activity.py --name demo --bursts 5

    # Only create the workspace (no worker):
    python tests/mock_activity.py --name demo --workspace-only

    # Keep the worker running after the test (manual stop):
    python tests/mock_activity.py --name demo --no-stop

Options
-------
--name          Project name  (default: mock_test)
--workspace     Path for the dummy workspace  (default: <engine_root>/mock_workspace/<name>)
--bursts        Number of edit bursts to simulate  (default: 3)
--burst-delay   Seconds to wait between bursts  (default: 2.5)
--workspace-only  Only create workspace files; do not start a worker
--no-stop       Leave the worker running after the test completes
--engine-root   Override engine root  (default: parent of tests/)
--json          Print final summary as JSON
"""

from __future__ import annotations

import argparse
import json
import logging
import random
import shutil
import string
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Resolve paths so the script works when invoked from any directory
# ---------------------------------------------------------------------------
_TESTS_DIR = Path(__file__).resolve().parent
_ENGINE_ROOT_DEFAULT = _TESTS_DIR.parent
sys.path.insert(0, str(_ENGINE_ROOT_DEFAULT.parent))

if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace", line_buffering=True)
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace", line_buffering=True)

from spd_analysis_engine.scripts.orchestrator import Supervisor
from spd_analysis_engine.scripts.storage_rotator import SessionDB, StorageRotator

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [MOCK ] %(levelname)-8s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Workspace scaffolding
# ---------------------------------------------------------------------------

_MAIN_PY_TEMPLATE = '''\
"""
main.py – generated by SPD mock_activity.py
Iteration: {iteration}  |  Generated: {ts}
"""

from utils import greet, compute


def main() -> None:
    """Entry point."""
    name = "SPD Engine"
    result = compute({a}, {b})
    print(greet(name))
    print(f"compute({a}, {b}) = {{result}}")


if __name__ == "__main__":
    main()
'''

_UTILS_PY_TEMPLATE = '''\
"""
utils.py – generated by SPD mock_activity.py
Iteration: {iteration}  |  Generated: {ts}
"""

import math


def greet(name: str) -> str:
    """Return a friendly greeting."""
    return f"Hello from {{name}}! (mock session iteration {iteration})"


def compute(x: float, y: float) -> float:
    """Perform a dummy computation."""
    return round(math.sqrt(abs(x ** 2 + y ** 2 + {noise})), 4)


def _internal_helper(data: list) -> list:
    """Filter and transform data."""
    return [item for item in data if isinstance(item, (int, float))]
'''


def _rand_int(lo: int = 1, hi: int = 100) -> int:
    return random.randint(lo, hi)


def _rand_noise() -> float:
    return round(random.uniform(0.0, 99.99), 4)


def scaffold_workspace(workspace: Path) -> None:
    """
    Create (or refresh) the dummy workspace with ``main.py`` and ``utils.py``.

    The files are given meaningful Python content so a real watchdog observer
    would record genuine EDIT events.

    Parameters
    ----------
    workspace : Directory that will contain the generated files.
    """
    workspace.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    a, b = _rand_int(), _rand_int()

    main_content = _MAIN_PY_TEMPLATE.format(
        iteration=0, ts=ts, a=a, b=b
    )
    utils_content = _UTILS_PY_TEMPLATE.format(
        iteration=0, ts=ts, noise=_rand_noise()
    )

    (workspace / "main.py").write_text(main_content, encoding="utf-8")
    (workspace / "utils.py").write_text(utils_content, encoding="utf-8")
    (workspace / "README.md").write_text(
        f"# Mock Workspace\n\nGenerated at {ts} by SPD mock_activity.py\n",
        encoding="utf-8",
    )
    logger.info("Workspace scaffolded at: %s", workspace)


def simulate_edit_burst(workspace: Path, iteration: int) -> list[str]:
    """
    Simulate a burst of file edits and return the list of modified paths.

    Each burst rewrites ``main.py`` and ``utils.py`` with new random values
    to ensure the content (and therefore file modification time) changes.

    Parameters
    ----------
    workspace : Directory containing the files.
    iteration : Burst counter (embedded in generated content for traceability).

    Returns
    -------
    list[str] – Paths of files that were written.
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    a, b = _rand_int(), _rand_int()
    noise = _rand_noise()
    modified: list[str] = []

    main_path = workspace / "main.py"
    main_path.write_text(
        _MAIN_PY_TEMPLATE.format(iteration=iteration, ts=ts, a=a, b=b),
        encoding="utf-8",
    )
    modified.append(str(main_path))

    utils_path = workspace / "utils.py"
    utils_path.write_text(
        _UTILS_PY_TEMPLATE.format(iteration=iteration, ts=ts, noise=noise),
        encoding="utf-8",
    )
    modified.append(str(utils_path))

    # Occasionally create a new ephemeral file to test CREATE events
    if random.random() < 0.4:
        rand_name = "".join(random.choices(string.ascii_lowercase, k=6))
        ephemeral = workspace / f"tmp_{rand_name}.py"
        ephemeral.write_text(
            f"# Ephemeral file – burst {iteration}\nDATA = {_rand_int()}\n",
            encoding="utf-8",
        )
        modified.append(str(ephemeral))

    logger.info("Burst #%s: wrote %d files", iteration, len(modified))
    return modified


# ---------------------------------------------------------------------------
# Session DB query helpers (used in post-test summary)
# ---------------------------------------------------------------------------

def _count_events(engine_root: Path, project_name: str) -> int:
    """Count events recorded in the project's current session DB."""
    rotator = StorageRotator(engine_root)
    db_path = rotator.current_path(project_name) / "session.db"
    if not db_path.exists():
        # Try last_run if current already got archived
        db_path = rotator.last_run_path(project_name) / "session.db"
    if not db_path.exists():
        return -1
    try:
        with SessionDB(db_path) as db:
            assert db._conn is not None
            cur = db._conn.execute("SELECT COUNT(*) FROM events")
            return cur.fetchone()[0]
    except Exception as exc:  # noqa: BLE001
        logger.warning("Could not count events: %s", exc)
        return -1


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="mock_activity",
        description="SPD Analysis Engine – mock workspace & activity generator",
    )
    p.add_argument("--name", default="mock_test", metavar="PROJECT_NAME",
                   help="Project name passed to the Supervisor (default: mock_test)")
    p.add_argument("--workspace", default=None, metavar="PATH",
                   help="Path to the dummy workspace directory (default: <engine_root>/mock_workspace/<name>)")
    p.add_argument("--bursts", type=int, default=3, metavar="N",
                   help="Number of edit bursts to simulate (default: 3)")
    p.add_argument("--burst-delay", type=float, default=2.5, metavar="SECONDS",
                   help="Seconds to wait between bursts (default: 2.5)")
    p.add_argument("--workspace-only", action="store_true", default=False,
                   help="Only scaffold the workspace; do not start a worker")
    p.add_argument("--no-stop", action="store_true", default=False,
                   help="Leave the worker running after the test")
    p.add_argument("--engine-root", default=str(_ENGINE_ROOT_DEFAULT),
                   metavar="DIR",
                   help=f"Engine root directory (default: {_ENGINE_ROOT_DEFAULT})")
    p.add_argument("--json", action="store_true", default=False,
                   help="Print the final summary as JSON")
    p.add_argument("--simulate-ai-burst", action="store_true", default=False,
                   help="Run Phase 2 integration test simulating realistic AI IDE bursts")
    return p


# ---------------------------------------------------------------------------
# Phase 2 AI IDE Burst Simulation Integration Test
# ---------------------------------------------------------------------------

def run_simulate_ai_burst(
    engine_root: Path,
    project_name: str,
    workspace: Path,
    json_output: bool = False,
) -> int:
    """
    Phase 2 Integration Test: Simulates AI IDE prompt bursts, debounce bundling,
    diff calculations, entrypoint tracking, SQLite storage, and patch persistence.
    """
    print(f"\n{'=' * 65}")
    print("  PHASE 2 INTEGRATION TEST: AI IDE Prompt Burst Simulation")
    print(f"{'=' * 65}")
    print(f"Project   : {project_name}")
    print(f"Workspace : {workspace}")
    print(f"Engine    : {engine_root}\n")

    # Step 1: Clean and scaffold workspace
    if workspace.exists():
        shutil.rmtree(workspace, ignore_errors=True)
    scaffold_workspace(workspace)
    print("[1/6] Workspace scaffolded with initial main.py and utils.py")

    # Step 2: Start worker
    sup = Supervisor(engine_root)
    try:
        sup.stop_project(project_name)
    except Exception:
        pass

    print(f"[2/6] Launching worker for '{project_name}'...")
    try:
        start_result = sup.start_project(name=project_name, path=str(workspace), scaffold=True)
    except Exception as exc:
        print(f"[ERROR] Failed to start project: {exc}", file=sys.stderr)
        return 1

    worker_pid = start_result.get("pid")
    print(f"      Worker active | PID={worker_pid}")
    print("      Waiting 2.0s for baseline capture and file watcher startup...")
    time.sleep(2.0)

    # Step 3: Burst 1
    # Rapid edits within < 3.5s quiet window:
    # main.py -> sleep 0.5s -> utils.py -> sleep 0.5s -> create service.py
    print("\n[3/6] Simulating Burst 1 (AI IDE multi-file generation)...")
    t0 = time.monotonic()

    main_file = workspace / "main.py"
    utils_file = workspace / "utils.py"
    service_file = workspace / "service.py"

    # Edit main.py
    main_text = main_file.read_text(encoding="utf-8")
    main_file.write_text(
        "# [BURST 1] Added AI Generated import\nfrom service import AuthService\n\n" + main_text,
        encoding="utf-8",
    )
    print(f"      [{time.monotonic() - t0:.2f}s] Modified: main.py (entrypoint)")
    time.sleep(0.5)

    # Edit utils.py
    utils_text = utils_file.read_text(encoding="utf-8")
    utils_file.write_text(
        utils_text + "\n\ndef validate_token(token: str) -> bool:\n    return len(token) > 8\n",
        encoding="utf-8",
    )
    print(f"      [{time.monotonic() - t0:.2f}s] Modified: utils.py")
    time.sleep(0.5)

    # Create service.py
    service_file.write_text(
        '"""service.py - Generated by AI IDE prompt burst 1."""\n\n'
        'class AuthService:\n'
        '    def __init__(self, realm: str = "default") -> None:\n'
        '        self.realm = realm\n\n'
        '    def check(self, user: str) -> bool:\n'
        '        return user.strip() != ""\n',
        encoding="utf-8",
    )
    print(f"      [{time.monotonic() - t0:.2f}s] Created : service.py")

    print("      Waiting 4.5s for 3.5s sliding debounce timer to fire...")
    time.sleep(4.5)

    # Step 4: Burst 2
    # Single-file edit after quiet window has closed
    print("\n[4/6] Simulating Burst 2 (Follow-up prompt modifying main.py)...")
    t1 = time.monotonic()
    main_text2 = main_file.read_text(encoding="utf-8")
    main_file.write_text(
        main_text2 + "\n# [BURST 2] Follow-up prompt edit\nDEBUG_MODE = True\n",
        encoding="utf-8",
    )
    print(f"      [{time.monotonic() - t1:.2f}s] Modified: main.py")

    print("      Waiting 4.5s for 3.5s sliding debounce timer to fire...")
    time.sleep(4.5)

    # Step 5: Verification
    print("\n[5/6] Verifying SQLite session events, patches, and diff files...")
    rotator = StorageRotator(engine_root)
    proj_dir = rotator.current_path(project_name)
    db_path = proj_dir / "session.db"
    patches_dir = proj_dir / "patches"

    failures: list[str] = []

    if not db_path.exists():
        failures.append(f"Database not found at: {db_path}")
        print(f"[FAIL] {failures[-1]}")
    else:
        with SessionDB(db_path) as db:
            assert db._conn is not None
            cur = db._conn.execute(
                "SELECT id, session_id, event_type, timestamp, first_file_touched, summary "
                "FROM events ORDER BY id ASC"
            )
            events = cur.fetchall()

            print(f"      Found {len(events)} event(s) in events table.")
            if len(events) != 2:
                failures.append(f"Expected exactly 2 bundled events, but got {len(events)}")
                print(f"      [FAIL] Expected 2 events, got {len(events)}")
            else:
                print("      [PASS] Exactly 2 bundled events recorded.")

            if len(events) >= 1:
                ev1 = events[0]
                ev1_id = ev1["id"]
                ev1_first = ev1["first_file_touched"]
                print(f"      Event #1: id={ev1_id}, first_file={ev1_first}, summary={ev1['summary']}")
                if ev1_first != "main.py":
                    failures.append(f"Event #1 first_file_touched expected 'main.py', got {ev1_first!r}")
                    print(f"      [FAIL] Event #1 entrypoint is {ev1_first!r}, expected 'main.py'")
                else:
                    print("      [PASS] Event #1 entrypoint correctly identified as 'main.py'")

                patches1 = db.get_patches(ev1_id)
                patch_files1 = [p["file_path"] for p in patches1]
                print(f"      Event #1 patches in DB: {patch_files1}")
                for expected_f in ["main.py", "utils.py", "service.py"]:
                    if expected_f not in patch_files1:
                        failures.append(f"Event #1 patch for '{expected_f}' missing from DB")
                        print(f"      [FAIL] Missing patch for {expected_f}")
                    else:
                        print(f"      [PASS] Patch recorded for {expected_f}")

                pfile1 = patches_dir / f"event_{ev1_id}.patch"
                if not pfile1.exists():
                    failures.append(f"Disk patch file not found: {pfile1}")
                    print(f"      [FAIL] Disk patch file missing: {pfile1}")
                else:
                    pcontent1 = pfile1.read_text(encoding="utf-8")
                    if "main.py" in pcontent1 and "service.py" in pcontent1:
                        print(f"      [PASS] Disk patch file event_{ev1_id}.patch verified ({len(pcontent1)} bytes)")
                    else:
                        failures.append(f"Disk patch file event_{ev1_id}.patch missing diff contents")
                        print("      [FAIL] Disk patch file missing expected file diffs")

            if len(events) >= 2:
                ev2 = events[1]
                ev2_id = ev2["id"]
                ev2_first = ev2["first_file_touched"]
                print(f"      Event #2: id={ev2_id}, first_file={ev2_first}, summary={ev2['summary']}")
                if ev2_first != "main.py":
                    failures.append(f"Event #2 first_file_touched expected 'main.py', got {ev2_first!r}")
                    print(f"      [FAIL] Event #2 entrypoint is {ev2_first!r}, expected 'main.py'")
                else:
                    print("      [PASS] Event #2 entrypoint correctly identified as 'main.py'")

                patches2 = db.get_patches(ev2_id)
                patch_files2 = [p["file_path"] for p in patches2]
                print(f"      Event #2 patches in DB: {patch_files2}")
                if "main.py" not in patch_files2:
                    failures.append("Event #2 patch for 'main.py' missing from DB")
                    print("      [FAIL] Event #2 missing patch for main.py")
                else:
                    print("      [PASS] Event #2 patch recorded for main.py")

                pfile2 = patches_dir / f"event_{ev2_id}.patch"
                if not pfile2.exists():
                    failures.append(f"Disk patch file not found: {pfile2}")
                    print(f"      [FAIL] Disk patch file missing: {pfile2}")
                else:
                    pcontent2 = pfile2.read_text(encoding="utf-8")
                    if "DEBUG_MODE" in pcontent2:
                        print(f"      [PASS] Disk patch file event_{ev2_id}.patch verified ({len(pcontent2)} bytes)")
                    else:
                        failures.append("Disk patch file event_2.patch missing DEBUG_MODE diff")
                        print("      [FAIL] Disk patch file missing DEBUG_MODE diff")

    # Step 6: Stop worker and verify archiving
    print("\n[6/6] Stopping worker and testing directory archiving...")
    stop_result = sup.stop_project(project_name)
    print(f"      Worker stopped | exit_code={stop_result.get('exit_code')}")

    last_run_dir = rotator.last_run_path(project_name)
    if not (last_run_dir / "session.db").exists():
        failures.append(f"Archived session.db not found in {last_run_dir}")
        print(f"      [FAIL] Archived session.db missing in {last_run_dir}")
    else:
        print(f"      [PASS] Project archived to last_run/{last_run_dir.name} successfully")

    # Final verdict
    print(f"\n{'=' * 65}")
    if not failures:
        print("  >>> ALL PHASE 2 INTEGRATION TESTS PASSED (100% SUCCESS) <<<")
        print(f"{'=' * 65}\n")
        return 0
    else:
        print(f"  >>> INTEGRATION TEST FAILED WITH {len(failures)} ERROR(S) <<<")
        for f in failures:
            print(f"   - {f}")
        print(f"{'=' * 65}\n")
        return 1


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    engine_root = Path(args.engine_root).resolve()

    project_name = args.name if (args.name != "mock_test" or not args.simulate_ai_burst) else "test_ai_burst"
    workspace = (
        Path(args.workspace).resolve()
        if args.workspace
        else engine_root / "mock_workspace" / project_name
    )

    if args.simulate_ai_burst:
        return run_simulate_ai_burst(
            engine_root=engine_root,
            project_name=project_name,
            workspace=workspace,
            json_output=args.json,
        )

    summary: dict = {
        "project":      args.name,
        "workspace":    str(workspace),
        "engine_root":  str(engine_root),
        "bursts":       args.bursts,
        "start_ts":     datetime.now(timezone.utc).isoformat(),
        "events_in_db": None,
        "worker_pid":   None,
        "stopped":      False,
    }

    # ------------------------------------------------------------------
    # Step 1 – Scaffold workspace
    # ------------------------------------------------------------------
    print(f"\n[MOCK] Scaffolding workspace at: {workspace}")
    scaffold_workspace(workspace)

    if args.workspace_only:
        print("[MOCK] --workspace-only flag set. Exiting after scaffold.")
        if args.json:
            print(json.dumps(summary, indent=2))
        return 0

    # ------------------------------------------------------------------
    # Step 2 – Start worker
    # ------------------------------------------------------------------
    sup = Supervisor(engine_root)
    print(f"[MOCK] Starting worker for project '{args.name}' …")

    try:
        result = sup.start_project(
            name=args.name,
            path=str(workspace),
            scaffold=True,
        )
    except ValueError as exc:
        print(f"[MOCK][ERROR] {exc}", file=sys.stderr)
        return 1

    summary["worker_pid"] = result["pid"]
    print(f"[MOCK] Worker started | PID={result['pid']}")

    # Give the worker time to emit its startup heartbeat
    print("[MOCK] Waiting 1.5s for worker startup heartbeat …")
    time.sleep(1.5)

    # ------------------------------------------------------------------
    # Step 3 – Edit bursts
    # ------------------------------------------------------------------
    print(f"\n[MOCK] Simulating {args.bursts} edit burst(s) "
          f"with {args.burst_delay}s delay between them …")

    for i in range(1, args.bursts + 1):
        files = simulate_edit_burst(workspace, iteration=i)
        print(f"  Burst {i}/{args.bursts}: modified {len(files)} file(s)")
        if i < args.bursts:
            time.sleep(args.burst_delay)

    # ------------------------------------------------------------------
    # Step 4 – Report status
    # ------------------------------------------------------------------
    time.sleep(0.5)  # let the last heartbeat arrive
    statuses = sup.get_status(args.name)
    if statuses:
        s = statuses[0]
        print(
            f"\n[MOCK] Worker status | alive={s['alive']} | "
            f"uptime={s['uptime_s']:.1f}s | "
            f"heartbeat_age={s['last_heartbeat_s']:.1f}s | "
            f"memory={s.get('memory_mb')} MB"
        )

    # ------------------------------------------------------------------
    # Step 5 – (Optional) Stop worker and archive
    # ------------------------------------------------------------------
    if args.no_stop:
        print(
            f"\n[MOCK] --no-stop flag set. Worker (PID {result['pid']}) "
            "is still running.\n"
            f"  Stop it with:  python start.py stop --project {args.name}"
        )
    else:
        print(f"\n[MOCK] Stopping worker for '{args.name}' …")
        stop_result = sup.stop_project(args.name)
        summary["stopped"] = True
        print(
            f"[MOCK] Worker stopped | exit_code={stop_result['exit_code']}"
        )

    # ------------------------------------------------------------------
    # Step 6 – Count DB events (post-archive, look in last_run)
    # ------------------------------------------------------------------
    event_count = _count_events(engine_root, args.name)
    summary["events_in_db"] = event_count
    summary["end_ts"] = datetime.now(timezone.utc).isoformat()

    if args.json:
        print("\n" + json.dumps(summary, indent=2))
    else:
        print("\n" + "-" * 60)
        print("  MOCK ACTIVITY SUMMARY")
        print("-" * 60)
        print(f"  Project      : {summary['project']}")
        print(f"  Workspace    : {summary['workspace']}")
        print(f"  Worker PID   : {summary['worker_pid']}")
        print(f"  Bursts run   : {args.bursts}")
        print(f"  Events in DB : {event_count if event_count >= 0 else 'N/A'}")
        print(f"  Worker stopped: {summary['stopped']}")
        print("-" * 60 + "\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
