/**
 * SPD Analysis Engine — Centralized DOM Registry (Lazy Evaluated Getters)
 */

export const DOM = {
  // Navigation & Sidebar
  get btnToggleSidebar() { return document.getElementById('btn-toggle-sidebar'); },
  get sidebar() { return document.querySelector('.sidebar'); },
  get sidebarToggleIcon() { return document.getElementById('sidebar-toggle-icon'); },
  get navButtons() { return document.querySelectorAll('.nav-item'); },
  get tabViews() { return document.querySelectorAll('.tab-view'); },
  get navEventCount() { return document.getElementById('nav-event-count'); },
  get navExecCount() { return document.getElementById('nav-exec-count'); },

  // Powers Ribbon
  get powerPillEdits() { return document.getElementById('power-pill-edits'); },
  get powerPillReads() { return document.getElementById('power-pill-reads'); },
  get powerPillExec() { return document.getElementById('power-pill-exec'); },
  get powerPillGit() { return document.getElementById('power-pill-git'); },

  // Header
  get headerProjectName() { return document.getElementById('header-project-name'); },
  get headerTierPill() { return document.getElementById('header-tier-pill'); },
  get headerPathVal() { return document.getElementById('header-path-val'); },
  get headerPid() { return document.getElementById('header-pid'); },
  get headerUptime() { return document.getElementById('header-uptime'); },
  get headerMem() { return document.getElementById('header-mem'); },
  get headerHb() { return document.getElementById('header-hb'); },
  get headerCompactTel() { return document.getElementById('header-compact-tel'); },
  get btnHeaderResume() { return document.getElementById('btn-header-resume'); },
  get btnHeaderStop() { return document.getElementById('btn-header-stop'); },
  get btnHeaderAiSettings() { return document.getElementById('btn-header-ai-settings'); },
  get btnHeaderGitSettings() { return document.getElementById('btn-header-git-settings'); },
  get btnHeaderPushGit() { return document.getElementById('btn-header-push-git'); },
  get btnHeaderTrash() { return document.getElementById('btn-header-trash'); },
  get headerTrashCount() { return document.getElementById('header-trash-count') || document.getElementById('badge-trash-count'); },
  get badgeTrashCount() { return document.getElementById('badge-trash-count') || document.getElementById('header-trash-count'); },
  get btnHeaderDeleteProj() { return document.getElementById('btn-header-delete-proj'); },

  // Sidebar Projects & Accordions
  get projectFilterInput() { return document.getElementById('project-filter-input'); },
  get btnRefreshProjects() { return document.getElementById('btn-refresh-projects'); },
  get countCurrent() { return document.getElementById('count-current'); },
  get countLastRun() { return document.getElementById('count-last-run'); },
  get countHistory() { return document.getElementById('count-history'); },
  get tierCurrentItems() { return document.getElementById('tier-current-items'); },
  get tierLastRunItems() { return document.getElementById('tier-last-run-items'); },
  get tierHistoryItems() { return document.getElementById('tier-history-items'); },
  get accordionCurrent() { return document.getElementById('accordion-current'); },
  get accordionLastRun() { return document.getElementById('accordion-last-run'); },
  get accordionHistory() { return document.getElementById('accordion-history'); },

  // Dashboard View
  get dashActiveCount() { return document.getElementById('dash-active-count'); },
  get dashEventCount() { return document.getElementById('dash-event-count'); },
  get dashPatchCount() { return document.getElementById('dash-patch-count'); },
  get detailSlug() { return document.getElementById('detail-slug'); },
  get detailTier() { return document.getElementById('detail-tier'); },
  get detailPath() { return document.getElementById('detail-path'); },
  get detailSessionId() { return document.getElementById('detail-session-id'); },
  get detailPid() { return document.getElementById('detail-pid'); },
  get detailMemory() { return document.getElementById('detail-memory'); },
  get dashRecentEvents() { return document.getElementById('dash-recent-events'); },
  get btnTelemetryResume() { return document.getElementById('btn-telemetry-resume'); },
  get btnExportSession() { return document.getElementById('btn-export-session'); },
  get btnViewAllTimeline() { return document.getElementById('btn-view-all-timeline'); },
  get btnBatchAnalyzeSession() { return document.getElementById('btn-batch-analyze-session'); },

  // Project Configuration & Specs Card
  get cardProjectSpecs() { return document.getElementById('card-project-specs'); },
  get specMonitoredPath() { return document.getElementById('spec-monitored-path'); },
  get specAiProfile() { return document.getElementById('spec-ai-profile'); },
  get specDebounceWindow() { return document.getElementById('spec-debounce-window'); },
  get specPowersChecklist() { return document.getElementById('spec-powers-checklist'); },
  get specCheckEdits() { return document.getElementById('spec-check-edits'); },
  get specCheckReads() { return document.getElementById('spec-check-reads'); },
  get specCheckExec() { return document.getElementById('spec-check-exec'); },
  get specCheckGit() { return document.getElementById('spec-check-git'); },
  get specGithubRemote() { return document.getElementById('spec-github-remote'); },
  get specLastPushStatus() { return document.getElementById('spec-last-push-status'); },
  get btnSpecsPushGh() { return document.getElementById('btn-specs-push-gh'); },

  // Real-Time Live Activity Stream
  get cardLiveActivity() { return document.getElementById('card-live-activity'); },
  get liveTickerFeed() { return document.getElementById('live-ticker-feed'); },
  get liveActionCount() { return document.getElementById('live-action-count'); },

  // Debounce Burst Monitor
  get cardDebounceMonitor() { return document.getElementById('card-debounce-monitor'); },
  get debounceMonitorTitle() { return document.getElementById('debounce-monitor-title'); },
  get debouncePulse() { return document.getElementById('debounce-pulse'); },
  get debounceStatusBadge() { return document.getElementById('debounce-status-badge'); },
  get btnSealBurstNow() { return document.getElementById('btn-seal-burst-now'); },
  get debounceProgressFill() { return document.getElementById('debounce-progress-fill'); },
  get debounceStatusDesc() { return document.getElementById('debounce-status-desc'); },
  get debounceCountdownText() { return document.getElementById('debounce-countdown-text'); },

  // Timeline View
  get timelineContainer() { return document.getElementById('timeline-container'); },
  get timelineFilterGroup() { return document.getElementById('timeline-filter-group'); },
  get timelineSearchInput() { return document.getElementById('timeline-search-input'); },
  get timelineFilterPills() { return document.querySelectorAll('.filter-pill'); },
  get btnRefreshTimeline() { return document.getElementById('btn-refresh-timeline'); },
  get timelineReadsList() { return document.getElementById('timeline-reads-list'); },
  get timelineReadCount() { return document.getElementById('timeline-read-count'); },

  // Terminal View
  get terminalFeedContainer() { return document.getElementById('terminal-feed-container'); },
  get terminalSearchInput() { return document.getElementById('terminal-search-input'); },
  get btnRefreshTerminal() { return document.getElementById('btn-refresh-terminal'); },

  // Diff Viewer View
  get diffSessionSelect() { return document.getElementById('diff-session-select'); },
  get diffBurstSelect() { return document.getElementById('diff-burst-select'); },
  get diffBurstCount() { return document.getElementById('diff-burst-count'); },
  get diffEventSelect() { return document.getElementById('diff-burst-select'); },
  get diffFileCount() { return document.getElementById('diff-file-count'); },
  get diffFilesList() { return document.getElementById('diff-files-list'); },
  get diffCurrentFileName() { return document.getElementById('diff-current-file-name'); },
  get diffCodeContainer() { return document.getElementById('diff-code-container'); },
  get statAdditions() { return document.getElementById('stat-additions'); },
  get statDeletions() { return document.getElementById('stat-deletions'); },
  get diffAiSlot() { return document.getElementById('diff-ai-slot'); },
  get btnAnalyzeFile() { return document.getElementById('btn-analyze-file') || document.getElementById('btn-analyze-active-file'); },
  get btnBatchAnalyzeFiles() { return document.getElementById('btn-batch-analyze-files') || document.getElementById('btn-analyze-checked-files'); },
  get btnAnalyzeActiveFile() { return document.getElementById('btn-analyze-active-file') || document.getElementById('btn-analyze-file'); },
  get btnAnalyzeCheckedFiles() { return document.getElementById('btn-analyze-checked-files') || document.getElementById('btn-batch-analyze-files'); },
  get btnOverviewBurstFiles() { return document.getElementById('btn-overview-burst-files'); },
  get btnOverviewFiles() { return document.getElementById('btn-overview-burst-files') || document.getElementById('btn-overview-files'); },
  get chkSelectAllFiles() { return document.getElementById('chk-select-all-files'); },
  get fileSelectAllRow() { return document.getElementById('file-select-all-row'); },
  get checkedFilesCount() { return document.getElementById('checked-files-count'); },
  get diffFileAiSlot() { return document.getElementById('diff-file-ai-slot'); },

  // Logs View
  get logsTerminal() { return document.getElementById('logs-terminal'); },
  get chkAutoscroll() { return document.getElementById('chk-autoscroll'); },
  get btnCopyLogs() { return document.getElementById('btn-copy-logs'); },
  get btnRefreshLogs() { return document.getElementById('btn-refresh-logs'); },

  // Modal: New Session
  get btnNewSession() { return document.getElementById('btn-new-session'); },
  get modalNewSession() { return document.getElementById('modal-new-session'); },
  get modalCloseBtn() { return document.getElementById('modal-close-btn'); },
  get modalCancelBtn() { return document.getElementById('modal-cancel-btn'); },
  get formNewSession() { return document.getElementById('form-new-session'); },
  get inpProjectName() { return document.getElementById('inp-project-name'); },
  get slugPreview() { return document.getElementById('slug-preview'); },
  get inpTargetPath() { return document.getElementById('inp-target-path'); },
  get chkScaffold() { return document.getElementById('chk-scaffold'); },
  get rngDebounce() { return document.getElementById('rng-debounce'); },
  get debounceValDisplay() { return document.getElementById('debounce-val-display'); },
  get selIdeProfile() { return document.getElementById('sel-ide-profile'); },
  get groupCustomIdeMarker() { return document.getElementById('group-custom-ide-marker'); },
  get inpCustomIdeMarker() { return document.getElementById('inp-custom-ide-marker'); },
  get modalError() { return document.getElementById('modal-error'); },
  get modalSpinner() { return document.getElementById('modal-spinner'); },
  get modalSubmitBtn() { return document.getElementById('modal-submit-btn'); },
  get chkPowerEdits() { return document.getElementById('chk-power-edits'); },
  get chkPowerReads() { return document.getElementById('chk-power-reads'); },
  get chkPowerExec() { return document.getElementById('chk-power-exec'); },
  get chkPowerShadowGit() { return document.getElementById('chk-power-shadow-git'); },
  get chkPowerGitInit() { return document.getElementById('chk-power-git-init'); },

  // Modal: Git Settings
  get modalGitSettings() { return document.getElementById('modal-git-settings'); },
  get modalGitSettingsClose() { return document.getElementById('modal-git-settings-close'); },
  get modalGitSettingsCancel() { return document.getElementById('modal-git-settings-cancel'); },
  get formGitSettings() { return document.getElementById('form-git-settings'); },
  get inpGitUsername() { return document.getElementById('inp-git-username'); },
  get inpGitToken() { return document.getElementById('inp-git-token'); },
  get inpGitDefaultRemote() { return document.getElementById('inp-git-default-remote'); },
  get inpGitDefaultBranch() { return document.getElementById('inp-git-default-branch'); },
  get chkGitAutoChangelog() { return document.getElementById('chk-git-auto-changelog'); },
  get inpGitTestUrl() { return document.getElementById('inp-git-test-url'); },
  get btnTestGitConnection() { return document.getElementById('btn-test-git-connection'); },
  get gitTestStatus() { return document.getElementById('git-test-status'); },
  get btnSaveGitConfig() { return document.getElementById('btn-save-git-config'); },

  // Modal: Milestone Sync Review
  get modalSyncReview() { return document.getElementById('modal-sync-review'); },
  get modalSyncReviewClose() { return document.getElementById('modal-sync-review-close'); },
  get modalSyncCancel() { return document.getElementById('modal-sync-cancel'); },
  get btnConfirmSyncPush() { return document.getElementById('btn-confirm-sync-push'); },
  get syncEventsCount() { return document.getElementById('sync-events-count'); },
  get syncProviderBadge() { return document.getElementById('sync-provider-badge'); },
  get inpSyncCommitTitle() { return document.getElementById('inp-sync-commit-title'); },
  get inpSyncCommitBody() { return document.getElementById('inp-sync-commit-body'); },
  get inpSyncChangelogContent() { return document.getElementById('inp-sync-changelog-content'); },
  get inpSyncRemote() { return document.getElementById('inp-sync-remote'); },
  get inpSyncBranch() { return document.getElementById('inp-sync-branch'); },
  get chkSyncAutoCreateRepo() { return document.getElementById('chk-sync-auto-create-repo'); },
  get syncError() { return document.getElementById('sync-error'); },
  get syncSpinner() { return document.getElementById('sync-spinner'); },

  // Push Stepper Progress Bar
  get syncStepperContainer() { return document.getElementById('sync-stepper-container'); },
  get syncStepperFill() { return document.getElementById('sync-stepper-fill'); },
  get syncStepperMsg() { return document.getElementById('sync-stepper-msg'); },
  get step1() { return document.getElementById('step-1'); },
  get step2() { return document.getElementById('step-2'); },
  get step3() { return document.getElementById('step-3'); },

  // Modal: AI Settings
  get modalAiSettings() { return document.getElementById('modal-ai-settings'); },
  get modalAiSettingsClose() { return document.getElementById('modal-ai-settings-close'); },
  get modalAiSettingsCancel() { return document.getElementById('modal-ai-settings-cancel'); },
  get formAiSettings() { return document.getElementById('form-ai-settings'); },
  get selAiProvider() { return document.getElementById('sel-ai-provider'); },
  get boxProviderOllama() { return document.getElementById('box-provider-ollama'); },
  get boxProviderGemini() { return document.getElementById('box-provider-gemini'); },
  get boxProviderHeuristic() { return document.getElementById('box-provider-heuristic'); },
  get inpOllamaUrl() { return document.getElementById('inp-ollama-url'); },
  get inpOllamaModel() { return document.getElementById('inp-ollama-model'); },
  get btnTestOllama() { return document.getElementById('btn-test-ollama'); },
  get ollamaTestStatus() { return document.getElementById('ollama-test-status'); },
  get selGeminiKeyVault() { return document.getElementById('sel-gemini-key-vault'); },
  get btnDeleteGeminiKey() { return document.getElementById('btn-delete-gemini-key'); },
  get inpGeminiKey() { return document.getElementById('inp-gemini-key'); },
  get lblGeminiKey() { return document.getElementById('lbl-gemini-key'); },
  get helpGeminiKey() { return document.getElementById('help-gemini-key'); },
  get geminiActiveKeyInfo() { return document.getElementById('gemini-active-key-info'); },
  get selGeminiModel() { return document.getElementById('sel-gemini-model'); },
  get btnTestGemini() { return document.getElementById('btn-test-gemini'); },
  get geminiTestStatus() { return document.getElementById('gemini-test-status'); },
  get btnSaveAiConfig() { return document.getElementById('btn-save-ai-config'); },

  // Batch Progress Box
  get batchProgressContainer() { return document.getElementById('batch-progress-container'); },
  get batchSpinner() { return document.getElementById('batch-spinner'); },
  get batchProgressTitle() { return document.getElementById('batch-progress-title'); },
  get batchProgressPct() { return document.getElementById('batch-progress-pct'); },
  get btnBatchRetry() { return document.getElementById('btn-batch-retry'); },
  get batchProgressFill() { return document.getElementById('batch-progress-fill'); },
  get batchProgressDetail() { return document.getElementById('batch-progress-detail'); },
  get batchProgressTime() { return document.getElementById('batch-progress-time'); },

  // Modal: Delete Project
  get modalDeleteProject() { return document.getElementById('modal-delete-project'); },
  get modalDeleteProjectClose() { return document.getElementById('modal-delete-project-close'); },
  get modalDeleteProjectCancel() { return document.getElementById('modal-delete-project-cancel'); },
  get delModalProjectName() { return document.getElementById('del-modal-project-name'); },
  get deleteBurstsContainer() { return document.getElementById('delete-bursts-container'); },
  get deleteBurstsList() { return document.getElementById('delete-bursts-list'); },
  get btnSelectAllBursts() { return document.getElementById('btn-select-all-bursts'); },
  get deleteSessionContainer() { return document.getElementById('delete-session-container'); },
  get selDeleteSessionTarget() { return document.getElementById('sel-delete-session-target'); },
  get deleteRemoteOption() { return document.getElementById('delete-remote-option'); },
  get chkDeleteRemoteGithub() { return document.getElementById('chk-delete-remote-github'); },
  get deleteProjectError() { return document.getElementById('delete-project-error'); },
  get deleteProjectSpinner() { return document.getElementById('delete-project-spinner'); },
  get btnConfirmDeleteProject() { return document.getElementById('btn-confirm-delete-project'); },

  // Modal: Trash Bin
  get modalTrashBin() { return document.getElementById('modal-trash-bin'); },
  get modalTrashBinClose() { return document.getElementById('modal-trash-bin-close'); },
  get btnEmptyTrash() { return document.getElementById('btn-empty-trash'); },
  get trashBinItemsContainer() { return document.getElementById('trash-bin-items-container'); },
  get trashBinError() { return document.getElementById('trash-bin-error'); },

  // Toasts & Status
  get toastContainer() { return document.getElementById('toast-container'); },
  get connStatus() { return document.getElementById('connection-status'); },
  get connText() { return document.getElementById('conn-text'); },

  // Floating Global Job Tray
  get globalJobTray() { return document.getElementById('global-job-tray'); },
  get traySpinner() { return document.getElementById('tray-spinner'); },
  get trayTitle() { return document.getElementById('tray-title'); },
  get trayCloseBtn() { return document.getElementById('tray-close-btn'); },
  get trayProjectName() { return document.getElementById('tray-project-name'); },
  get trayProgressBar() { return document.getElementById('tray-progress-bar'); },
  get trayCounts() { return document.getElementById('tray-counts'); },
  get trayPercent() { return document.getElementById('tray-percent'); },
  get trayCooldownBadge() { return document.getElementById('tray-cooldown-badge'); },
  get trayCooldownText() { return document.getElementById('tray-cooldown-text'); },
};
